### ISSUE TITLE
Support ActionLib

### ISSUE THREAD

**Issue by leospalteholz** [wesgood/RBSManager#1]
In addition to support for Subscribe/Publish Topics and Service Calls, it would be great if RBSManager supported the client side of Actions as defined by actionlib.   http://wiki.ros.org/actionlib

**Comment by wesgood** [comment]
Very interesting suggestion! My ROS knowledge has skipped the actionlib function but I can see now that it would be very useful. I will have to investigate how ROSBridge handles the functions because it is a different mechanism (feedback vs subscribing). I will leave this item open for you to provide any info you have about what kind of actions you'd like to do and I will try to look into it.

**Comment by wesgood** [comment]
Hi there! I have looked into the ActionLib process and while I can see the value, it doesn't look like Rosbridge supports the function. You can see it here in the protocol document https://github.com/RobotWebTools/rosbridge_suite/blob/groovy-devel/ROSBRIDGE_PROTOCOL.md

I'd suggest checking with those developers to see if there are plans to bring the capability in. In the meantime I've found that a combo of service and publishers can provide a similar functionality.
